AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  EasySplitLogin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: easysplit-login
      Handler: bootstrap
      Runtime: go1.x
      CodeUri: ./
      Timeout: 30
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: "/easysplit-login"
            Method: get
  
  EasySplitSignup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: easysplit-login
      Handler: bootstrap
      Runtime: go1.x
      CodeUri: ./
      Timeout: 30
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: "/easysplit-login"   # 🔹 Change the path for signup
            Method: post    # 🔹 Use POST for signup (since it's creating data)

